---
Users:  # Users of Debile
    - name: Kiskadee Tool
      email: kiskadee@mail.com
      pgp: ABFFB743FAC03779FC3E4C2FFFB355162ACA0558
      ssl: 00000000000000000EADBEEF0000000000000000

Builders:  # Machines that can build
    - name: debile-slave
      maintainer: kiskadee@mail.com
      pgp: ABFFB743FAC03779FC3E4C2FFFB355162ACA0558
      ssl: 00000000000000000EADBEE00000000000000000

Suites:
    - name: unstable

Components:
    - name: main

Arches:
    - name: amd64

Checks:
    - name: lintian
      source: true
      binary: true
      build: false
    - name: cppcheck
      source: true
      binary: true
      build: false
    - name: vulnerabilities
      source: true
      binary: true
      build: false

Groups:
    - name: default
      maintainer: kiskadee@mail.com
      suites:
          - suite: unstable
            components:
                - main
            arches:
                - amd64
            checks:
                - vulnerabilities
